import{test}from"node:test";import assert from"node:assert/strict";import{readFileSync,readdirSync,statSync}from"node:fs";import{join}from"node:path";import{dashboardForRoles,safeNextPath}from"./portal-routing";
const root=process.cwd();
test("login destinations are role aware and reject open redirects",()=>{assert.equal(dashboardForRoles(["administrator"]),"/admin");assert.equal(dashboardForRoles(["manager"]),"/manager");assert.equal(dashboardForRoles(["assessment"]),"/assessment");assert.equal(dashboardForRoles(["staff"]),"/admin/assessments");assert.equal(dashboardForRoles(["customer_company"]),"/account");assert.equal(dashboardForRoles(["customer"]),"/account");assert.equal(dashboardForRoles(["applicant"]),"/account/assessments");assert.equal(safeNextPath("https://evil.example"),"/account");assert.equal(safeNextPath("//evil.example"),"/account");assert.equal(safeNextPath("/account/invoices"),"/account/invoices")});
test("regional_manager routes to its own workspace, but administrator still wins",()=>{assert.equal(dashboardForRoles(["regional_manager"]),"/regional-manager");assert.equal(dashboardForRoles(["regional_manager","administrator"]),"/admin");assert.equal(dashboardForRoles(["regional_manager","manager"]),"/regional-manager")});
test("requireAuth/authorizeApi enforce isBlocked (suspended customer or deactivated staff) before role checks",()=>{
  // portal-auth.ts pulls in next/navigation's redirect(), which cannot be
  // imported outside a Next runtime (breaks under plain tsx --test), so this
  // is verified by source inspection rather than by calling the functions.
  const source=readFileSync(join(root,"src/lib/portal-auth.ts"),"utf8");
  assert.match(source,/function isBlocked\(context: AuthContext\): boolean/);
  assert.match(source,/context\.customerStatus === "suspended" \|\| context\.staffActive === false/);
  assert.match(source,/export async function requireAuth[\s\S]*?if \(isBlocked\(context\)\) redirect\("\/login\?error=account_suspended"\)/);
  assert.match(source,/export async function authorizeApi[\s\S]*?if \(isBlocked\(context\)\) return \{ ok: false as const, status: 403 as const, error: "account_suspended" \}/);
});
test("login page does not bounce a blocked account back to its own dashboard (would infinite-redirect against requireAuth)",()=>{const source=readFileSync(join(root,"src/app/login/page.tsx"),"utf8");assert.match(source,/if \(existing && !isBlocked\(existing\)\) redirect/)});
test("login route rejects a suspended customer or deactivated staff member before returning a destination",()=>{const source=readFileSync(join(root,"src/app/api/auth/login/route.ts"),"utf8");assert.match(source,/customer\?\.status===["']suspended["']\|\|staff\?\.active===false/);assert.match(source,/account_suspended/);assert.match(source,/auth\.signOut\(\)/)});
test("manager/customer/subscription/personnel block routes are scoped to administrator, manager and regional_manager, with office ownership checks for regional managers",()=>{for(const file of["src/app/api/admin/customers/[id]/status/route.ts","src/app/api/admin/subscriptions/[id]/status/route.ts","src/app/api/admin/team/[id]/status/route.ts"]){const source=readFileSync(join(root,file),"utf8");assert.match(source,/authorizeApi\(\["administrator", "manager", "regional_manager"\]\)/);assert.match(source,/officeIds\.includes/)}});
test("account_blocking_and_offices migration widens role/status constraints and creates the offices schema",()=>{const sql=readFileSync(join(root,"supabase/migrations/20260802235317_account_blocking_and_offices.sql"),"utf8");for(const expected of["'suspended_manual'","create table if not exists public.offices","regional_manager_offices","'regional_manager'","grant select (active) on table public.staff_members to authenticated"]){assert.ok(sql.includes(expected),expected)}});
test("assessment application API enforces the database flag before persistence",()=>{const source=readFileSync(join(root,"src/lib/assessment-checkout.ts"),"utf8");assert.match(source,/featureEnabled\("initial_assessment_booking_enabled"\)/);assert.match(source,/assessment_booking_disabled/);assert.doesNotMatch(source,/createAssessmentCheckoutSession/)});
test("portal migration contains ownership RLS, private storage and safe defaults",()=>{const sql=readFileSync(join(root,"supabase/migrations/20260715225139_secure_customer_onboarding_portal.sql"),"utf8");for(const expected of["initial_assessment_booking_enabled', 'Initial assessment booking'","'customer_portal_enabled', 'Customer portal'","'subscription_checkout_enabled', 'Subscription checkout'","alter table public.subscription_proposals enable row level security","proposals_read_own","payments_read_own","assessment_storage_read_own","revoke insert, delete on table public.properties from authenticated"]){assert.ok(sql.includes(expected),expected)}assert.match(sql,/initial_assessment_booking_enabled'[\s\S]*?false/);assert.match(sql,/subscription_checkout_enabled'[\s\S]*?false/)});
test("customer-facing legacy estimate-request wording is absent",()=>{const files:string[]=[];const forbidden=new RegExp(["request a ","get a ","ask for a "].join("quote|")+"quote|quote request","i");function walk(path:string){for(const name of readdirSync(path)){const full=join(path,name);if(name==="node_modules"||name===".next")continue;const stat=statSync(full);if(stat.isDirectory())walk(full);else if(/\.(ts|tsx|md)$/.test(name)&&name!=="portal-security.test.ts")files.push(full)}}walk(join(root,"src"));for(const file of files){const value=readFileSync(file,"utf8");assert.doesNotMatch(value,forbidden,file)}});
test("public header always includes Login and My Account states",()=>{const nav=readFileSync(join(root,"src/components/layout/navbar.tsx"),"utf8");assert.match(nav,/dict\.login/);assert.match(nav,/dict\.myAccount/);assert.match(nav,/accountHref/)});
test("assessment reads do not require exposing staff rows to customers",()=>{const sql=readFileSync(join(root,"supabase/migrations/20260801160103_fix_authenticated_assessment_reads.sql"),"utf8");assert.match(sql,/security definer/);assert.match(sql,/private\.current_user_is_active_staff_member\(assigned_staff_id\)/);assert.match(sql,/revoke all on function[\s\S]*from public, anon, authenticated/);assert.doesNotMatch(sql,/grant select[\s\S]*staff_members[\s\S]*authenticated/)});
