import type { Locale } from "./config";
import type { CustomerSupportStatus, SupportCategory } from "@/lib/hospitality-support/types";

export type SupportCopy = {
  title: string; intro: string; newRequest: string; cancel: string;
  subject: string; category: string; description: string; descriptionHint: string;
  property: string; subscription: string; invoice: string; appointment: string; payment: string;
  contactMethod: string; phone: string; attachments: string; optional: string;
  submit: string; submitting: string; uploading: string; reply: string; sendReply: string; replyPlaceholder: string;
  all: string; filterLabel: string; sortLabel: string; latest: string; oldest: string; createdSort: string;
  emptyTitle: string; emptyBody: string; unavailable: string; createFailed: string; replyFailed: string;
  reference: string; createdLabel: string; updatedLabel: string; department: string; priority: string;
  unread: string; latestFromCustomer: string; latestFromSupport: string; conversation: string; information: string;
  nextAction: string; resolution: string; none: string; back: string; closedExplanation: string; createFollowUp: string;
  customerRole: string; supportRole: string; callRecord: string; systemEvent: string; download: string;
  attachmentError: string; categoryLabels: Record<SupportCategory, string>; statusLabels: Record<CustomerSupportStatus, string>;
  contactMethods: Record<"portal"|"email"|"phone"|"whatsapp", string>;
  priorityLabels: Record<"low"|"normal"|"high"|"urgent", string>;
};

const categories = (values: string[]): Record<SupportCategory, string> => Object.fromEntries([
  "cleaning_service", "subscription", "appointment", "invoice", "payment", "key_management", "smart_lock",
  "property_details", "employee_feedback", "damage_missing_item", "complaint", "technical_issue", "account_access", "other",
].map((key, index) => [key, values[index]])) as Record<SupportCategory, string>;

const statuses = (values: string[]): Record<CustomerSupportStatus, string> => ({
  open: values[0], waiting_support: values[1], waiting_customer: values[2], in_progress: values[3], resolved: values[4], closed: values[5],
});

const en: SupportCopy = {
  title:"Support requests",intro:"Keep every message, update, call note and attachment for one issue in a single support thread.",newRequest:"New support request",cancel:"Cancel",subject:"Subject",category:"Category",description:"Description",descriptionHint:"Tell us what happened, when it happened, what was involved, what you expected and the resolution you are requesting.",property:"Related property",subscription:"Related subscription",invoice:"Related invoice",appointment:"Related appointment",payment:"Related payment",contactMethod:"Preferred contact method",phone:"Phone number",attachments:"Attachments",optional:"Optional",submit:"Create support request",submitting:"Creating request…",uploading:"Uploading {progress}%",reply:"Reply",sendReply:"Send reply",replyPlaceholder:"Write your reply…",all:"All",filterLabel:"Filter",sortLabel:"Sort",latest:"Latest update",oldest:"Oldest update",createdSort:"Date created",emptyTitle:"No support requests yet",emptyBody:"Create a request when you need help. Your full conversation will stay together here.",unavailable:"Support information is temporarily unavailable. Your existing requests are safe. Please try again shortly.",createFailed:"We could not create the request. Your text and attachments are still available to retry.",replyFailed:"Your reply was not sent. It is still here so you can retry.",reference:"Ticket reference",createdLabel:"Created",updatedLabel:"Last update",department:"Support department",priority:"Priority",unread:"Unread",latestFromCustomer:"Latest message from you",latestFromSupport:"Latest message from Dar Tahara",conversation:"Conversation",information:"Request information",nextAction:"Next expected action",resolution:"Resolution summary",none:"Not provided",back:"Back to support",closedExplanation:"This request is permanently closed and can no longer receive replies.",createFollowUp:"Create a follow-up request",customerRole:"You",supportRole:"Dar Tahara Support",callRecord:"Phone call",systemEvent:"System update",download:"Download",attachmentError:"Use up to 5 JPG, PNG, WebP, PDF, text or MP4 files, no larger than 10 MB each.",
  categoryLabels:categories(["Cleaning service","Subscription","Appointment or rescheduling","Invoice","Payment","Key management","Smart lock","Property details","Employee feedback","Damage or missing item","Complaint","Technical issue","Account access","Other"]),
  statusLabels:statuses(["Open","Waiting for Dar Tahara","Waiting for your response","In progress","Resolved","Closed"]),
  contactMethods:{portal:"Portal",email:"Email",phone:"Phone",whatsapp:"WhatsApp"},
  priorityLabels:{low:"Low",normal:"Normal",high:"High",urgent:"Urgent"},
};

export const supportCopy: Record<Locale, SupportCopy> = {
  en,
  nl:{...en,title:"Supportverzoeken",intro:"Bewaar alle berichten, updates, gespreksnotities en bijlagen over één onderwerp in één supportgesprek.",newRequest:"Nieuw supportverzoek",cancel:"Annuleren",subject:"Onderwerp",category:"Categorie",description:"Beschrijving",descriptionHint:"Vertel wat er is gebeurd, wanneer, wat erbij betrokken was, wat u verwachtte en welke oplossing u vraagt.",property:"Gerelateerde woning",subscription:"Gerelateerd abonnement",invoice:"Gerelateerde factuur",appointment:"Gerelateerde afspraak",payment:"Gerelateerde betaling",contactMethod:"Voorkeurscontactmethode",phone:"Telefoonnummer",attachments:"Bijlagen",optional:"Optioneel",submit:"Supportverzoek aanmaken",submitting:"Verzoek aanmaken…",uploading:"Uploaden {progress}%",reply:"Antwoorden",sendReply:"Antwoord versturen",replyPlaceholder:"Schrijf uw antwoord…",all:"Alle",filterLabel:"Filter",sortLabel:"Sorteren",latest:"Laatste update",oldest:"Oudste update",createdSort:"Aanmaakdatum",emptyTitle:"Nog geen supportverzoeken",emptyBody:"Maak een verzoek aan wanneer u hulp nodig hebt. Het volledige gesprek blijft hier bij elkaar.",unavailable:"Supportinformatie is tijdelijk niet beschikbaar. Uw bestaande verzoeken zijn veilig. Probeer het binnenkort opnieuw.",createFailed:"Het verzoek kon niet worden aangemaakt. Uw tekst en bijlagen blijven beschikbaar om opnieuw te proberen.",replyFailed:"Uw antwoord is niet verzonden. Het blijft beschikbaar om opnieuw te proberen.",reference:"Ticketreferentie",createdLabel:"Aangemaakt",updatedLabel:"Laatste update",department:"Supportafdeling",priority:"Prioriteit",unread:"Ongelezen",latestFromCustomer:"Laatste bericht van u",latestFromSupport:"Laatste bericht van Dar Tahara",conversation:"Gesprek",information:"Verzoekinformatie",nextAction:"Volgende verwachte actie",resolution:"Samenvatting oplossing",none:"Niet opgegeven",back:"Terug naar support",closedExplanation:"Dit verzoek is definitief gesloten en kan geen antwoorden meer ontvangen.",createFollowUp:"Vervolgverzoek aanmaken",customerRole:"U",supportRole:"Dar Tahara Support",callRecord:"Telefoongesprek",systemEvent:"Systeemupdate",download:"Downloaden",attachmentError:"Gebruik maximaal 5 JPG-, PNG-, WebP-, PDF-, tekst- of MP4-bestanden van maximaal 10 MB per bestand.",categoryLabels:categories(["Schoonmaakdienst","Abonnement","Afspraak of verplaatsing","Factuur","Betaling","Sleutelbeheer","Slim slot","Woninggegevens","Feedback over medewerker","Schade of vermist item","Klacht","Technisch probleem","Accounttoegang","Overig"]),statusLabels:statuses(["Open","Wacht op Dar Tahara","Wacht op uw antwoord","In behandeling","Opgelost","Gesloten"])},
  fr:{...en,title:"Demandes d’assistance",intro:"Conservez tous les messages, mises à jour, notes d’appel et pièces jointes d’un même problème dans un seul fil.",newRequest:"Nouvelle demande",cancel:"Annuler",subject:"Objet",category:"Catégorie",description:"Description",descriptionHint:"Expliquez ce qui s’est passé, quand, ce qui était concerné, ce que vous attendiez et la solution souhaitée.",property:"Bien concerné",subscription:"Abonnement concerné",invoice:"Facture concernée",appointment:"Rendez-vous concerné",payment:"Paiement concerné",contactMethod:"Moyen de contact préféré",phone:"Numéro de téléphone",attachments:"Pièces jointes",optional:"Facultatif",submit:"Créer la demande",submitting:"Création…",uploading:"Téléversement {progress}%",reply:"Répondre",sendReply:"Envoyer la réponse",replyPlaceholder:"Écrivez votre réponse…",all:"Toutes",filterLabel:"Filtrer",sortLabel:"Trier",latest:"Dernière mise à jour",oldest:"Mise à jour la plus ancienne",createdSort:"Date de création",emptyTitle:"Aucune demande d’assistance",emptyBody:"Créez une demande lorsque vous avez besoin d’aide. Toute la conversation restera regroupée ici.",unavailable:"Les informations d’assistance sont temporairement indisponibles. Vos demandes existantes sont en sécurité. Réessayez bientôt.",createFailed:"La demande n’a pas pu être créée. Votre texte et vos pièces jointes restent disponibles pour réessayer.",replyFailed:"Votre réponse n’a pas été envoyée. Elle reste disponible pour réessayer.",reference:"Référence du ticket",createdLabel:"Créée",updatedLabel:"Dernière mise à jour",department:"Service d’assistance",priority:"Priorité",unread:"Non lu",latestFromCustomer:"Dernier message de votre part",latestFromSupport:"Dernier message de Dar Tahara",conversation:"Conversation",information:"Informations sur la demande",nextAction:"Prochaine action attendue",resolution:"Résumé de la résolution",none:"Non renseigné",back:"Retour à l’assistance",closedExplanation:"Cette demande est définitivement clôturée et ne peut plus recevoir de réponse.",createFollowUp:"Créer une demande de suivi",customerRole:"Vous",supportRole:"Assistance Dar Tahara",callRecord:"Appel téléphonique",systemEvent:"Mise à jour système",download:"Télécharger",attachmentError:"Ajoutez jusqu’à 5 fichiers JPG, PNG, WebP, PDF, texte ou MP4 de 10 Mo maximum chacun.",categoryLabels:categories(["Service de nettoyage","Abonnement","Rendez-vous ou reprogrammation","Facture","Paiement","Gestion des clés","Serrure intelligente","Détails du bien","Avis sur un employé","Dommage ou objet manquant","Réclamation","Problème technique","Accès au compte","Autre"]),statusLabels:statuses(["Ouverte","En attente de Dar Tahara","En attente de votre réponse","En cours","Résolue","Clôturée"])},
  es:{...en,title:"Solicitudes de soporte",intro:"Mantenga todos los mensajes, actualizaciones, notas de llamadas y archivos de un asunto en un solo hilo.",newRequest:"Nueva solicitud",cancel:"Cancelar",subject:"Asunto",category:"Categoría",description:"Descripción",descriptionHint:"Explique qué ocurrió, cuándo, qué estaba relacionado, qué esperaba y qué solución solicita.",property:"Propiedad relacionada",subscription:"Suscripción relacionada",invoice:"Factura relacionada",appointment:"Cita relacionada",payment:"Pago relacionado",contactMethod:"Método de contacto preferido",phone:"Número de teléfono",attachments:"Archivos adjuntos",optional:"Opcional",submit:"Crear solicitud",submitting:"Creando…",uploading:"Subiendo {progress}%",reply:"Responder",sendReply:"Enviar respuesta",replyPlaceholder:"Escriba su respuesta…",all:"Todas",filterLabel:"Filtrar",sortLabel:"Ordenar",latest:"Última actualización",oldest:"Actualización más antigua",createdSort:"Fecha de creación",emptyTitle:"No hay solicitudes de soporte",emptyBody:"Cree una solicitud cuando necesite ayuda. Toda la conversación permanecerá unida aquí.",unavailable:"La información de soporte no está disponible temporalmente. Sus solicitudes están seguras. Inténtelo de nuevo pronto.",createFailed:"No se pudo crear la solicitud. El texto y los archivos siguen disponibles para reintentar.",replyFailed:"La respuesta no se envió. Sigue aquí para que pueda reintentar.",reference:"Referencia del ticket",createdLabel:"Creada",updatedLabel:"Última actualización",department:"Departamento de soporte",priority:"Prioridad",unread:"Sin leer",latestFromCustomer:"Último mensaje suyo",latestFromSupport:"Último mensaje de Dar Tahara",conversation:"Conversación",information:"Información de la solicitud",nextAction:"Próxima acción prevista",resolution:"Resumen de la solución",none:"No indicado",back:"Volver a soporte",closedExplanation:"Esta solicitud está cerrada permanentemente y ya no admite respuestas.",createFollowUp:"Crear solicitud de seguimiento",customerRole:"Usted",supportRole:"Soporte de Dar Tahara",callRecord:"Llamada telefónica",systemEvent:"Actualización del sistema",download:"Descargar",attachmentError:"Use hasta 5 archivos JPG, PNG, WebP, PDF, texto o MP4 de un máximo de 10 MB cada uno.",categoryLabels:categories(["Servicio de limpieza","Suscripción","Cita o reprogramación","Factura","Pago","Gestión de llaves","Cerradura inteligente","Detalles de la propiedad","Opinión sobre empleado","Daño u objeto perdido","Queja","Problema técnico","Acceso a la cuenta","Otro"]),statusLabels:statuses(["Abierta","Esperando a Dar Tahara","Esperando su respuesta","En curso","Resuelta","Cerrada"])},
  de:{...en,title:"Supportanfragen",intro:"Bewahren Sie alle Nachrichten, Aktualisierungen, Anrufnotizen und Anhänge zu einem Anliegen in einem Supportverlauf auf.",newRequest:"Neue Supportanfrage",cancel:"Abbrechen",subject:"Betreff",category:"Kategorie",description:"Beschreibung",descriptionHint:"Beschreiben Sie, was wann passiert ist, was betroffen war, was Sie erwartet haben und welche Lösung Sie wünschen.",property:"Zugehörige Immobilie",subscription:"Zugehöriges Abonnement",invoice:"Zugehörige Rechnung",appointment:"Zugehöriger Termin",payment:"Zugehörige Zahlung",contactMethod:"Bevorzugte Kontaktart",phone:"Telefonnummer",attachments:"Anhänge",optional:"Optional",submit:"Supportanfrage erstellen",submitting:"Anfrage wird erstellt…",uploading:"Hochladen {progress}%",reply:"Antworten",sendReply:"Antwort senden",replyPlaceholder:"Schreiben Sie Ihre Antwort…",all:"Alle",filterLabel:"Filtern",sortLabel:"Sortieren",latest:"Neueste Aktualisierung",oldest:"Älteste Aktualisierung",createdSort:"Erstellungsdatum",emptyTitle:"Noch keine Supportanfragen",emptyBody:"Erstellen Sie bei Bedarf eine Anfrage. Der gesamte Verlauf bleibt hier zusammen.",unavailable:"Supportinformationen sind vorübergehend nicht verfügbar. Ihre bestehenden Anfragen sind sicher. Versuchen Sie es bald erneut.",createFailed:"Die Anfrage konnte nicht erstellt werden. Text und Anhänge bleiben für einen neuen Versuch erhalten.",replyFailed:"Ihre Antwort wurde nicht gesendet und bleibt für einen neuen Versuch erhalten.",reference:"Ticketreferenz",createdLabel:"Erstellt",updatedLabel:"Letzte Aktualisierung",department:"Supportabteilung",priority:"Priorität",unread:"Ungelesen",latestFromCustomer:"Letzte Nachricht von Ihnen",latestFromSupport:"Letzte Nachricht von Dar Tahara",conversation:"Verlauf",information:"Anfrageinformationen",nextAction:"Nächster erwarteter Schritt",resolution:"Lösungszusammenfassung",none:"Nicht angegeben",back:"Zurück zum Support",closedExplanation:"Diese Anfrage ist endgültig geschlossen und kann keine Antworten mehr empfangen.",createFollowUp:"Folgeanfrage erstellen",customerRole:"Sie",supportRole:"Dar Tahara Support",callRecord:"Telefonat",systemEvent:"Systemaktualisierung",download:"Herunterladen",attachmentError:"Verwenden Sie bis zu 5 JPG-, PNG-, WebP-, PDF-, Text- oder MP4-Dateien mit jeweils höchstens 10 MB.",categoryLabels:categories(["Reinigungsservice","Abonnement","Termin oder Verschiebung","Rechnung","Zahlung","Schlüsselverwaltung","Smart Lock","Immobiliendetails","Mitarbeiterfeedback","Schaden oder fehlender Gegenstand","Beschwerde","Technisches Problem","Kontozugriff","Sonstiges"]),statusLabels:statuses(["Offen","Wartet auf Dar Tahara","Wartet auf Ihre Antwort","In Bearbeitung","Gelöst","Geschlossen"])},
  pt:{...en,title:"Pedidos de apoio",intro:"Mantenha todas as mensagens, atualizações, notas de chamadas e anexos de um assunto num único tópico.",newRequest:"Novo pedido",cancel:"Cancelar",subject:"Assunto",category:"Categoria",description:"Descrição",descriptionHint:"Explique o que aconteceu, quando, o que estava envolvido, o que esperava e qual a solução pretendida.",property:"Propriedade relacionada",subscription:"Subscrição relacionada",invoice:"Fatura relacionada",appointment:"Marcação relacionada",payment:"Pagamento relacionado",contactMethod:"Método de contacto preferido",phone:"Número de telefone",attachments:"Anexos",optional:"Opcional",submit:"Criar pedido",submitting:"A criar…",uploading:"A carregar {progress}%",reply:"Responder",sendReply:"Enviar resposta",replyPlaceholder:"Escreva a sua resposta…",all:"Todos",filterLabel:"Filtrar",sortLabel:"Ordenar",latest:"Última atualização",oldest:"Atualização mais antiga",createdSort:"Data de criação",emptyTitle:"Ainda não existem pedidos",emptyBody:"Crie um pedido quando precisar de ajuda. Toda a conversa ficará reunida aqui.",unavailable:"A informação de apoio está temporariamente indisponível. Os seus pedidos estão seguros. Tente novamente em breve.",createFailed:"Não foi possível criar o pedido. O texto e os anexos continuam disponíveis para tentar novamente.",replyFailed:"A resposta não foi enviada. Continua aqui para poder tentar novamente.",reference:"Referência do pedido",createdLabel:"Criado",updatedLabel:"Última atualização",department:"Departamento de apoio",priority:"Prioridade",unread:"Não lido",latestFromCustomer:"Última mensagem sua",latestFromSupport:"Última mensagem da Dar Tahara",conversation:"Conversa",information:"Informação do pedido",nextAction:"Próxima ação esperada",resolution:"Resumo da resolução",none:"Não indicado",back:"Voltar ao apoio",closedExplanation:"Este pedido está encerrado permanentemente e já não aceita respostas.",createFollowUp:"Criar pedido de seguimento",customerRole:"Você",supportRole:"Apoio Dar Tahara",callRecord:"Chamada telefónica",systemEvent:"Atualização do sistema",download:"Transferir",attachmentError:"Use até 5 ficheiros JPG, PNG, WebP, PDF, texto ou MP4, com um máximo de 10 MB cada.",categoryLabels:categories(["Serviço de limpeza","Subscrição","Marcação ou reagendamento","Fatura","Pagamento","Gestão de chaves","Fechadura inteligente","Detalhes da propriedade","Avaliação de funcionário","Dano ou item em falta","Reclamação","Problema técnico","Acesso à conta","Outro"]),statusLabels:statuses(["Aberto","A aguardar a Dar Tahara","A aguardar a sua resposta","Em curso","Resolvido","Fechado"])},
  ar:{...en,title:"طلبات الدعم",intro:"احتفظ بجميع الرسائل والتحديثات وملاحظات المكالمات والمرفقات الخاصة بالمشكلة في محادثة دعم واحدة.",newRequest:"طلب دعم جديد",cancel:"إلغاء",subject:"الموضوع",category:"الفئة",description:"الوصف",descriptionHint:"اشرح ما حدث ومتى وما الذي كان معنيًا وما الذي توقعته والحل الذي تطلبه.",property:"العقار المرتبط",subscription:"الاشتراك المرتبط",invoice:"الفاتورة المرتبطة",appointment:"الموعد المرتبط",payment:"الدفع المرتبط",contactMethod:"طريقة التواصل المفضلة",phone:"رقم الهاتف",attachments:"المرفقات",optional:"اختياري",submit:"إنشاء طلب دعم",submitting:"جارٍ إنشاء الطلب…",uploading:"جارٍ الرفع {progress}%",reply:"رد",sendReply:"إرسال الرد",replyPlaceholder:"اكتب ردك…",all:"الكل",filterLabel:"تصفية",sortLabel:"ترتيب",latest:"آخر تحديث",oldest:"أقدم تحديث",createdSort:"تاريخ الإنشاء",emptyTitle:"لا توجد طلبات دعم بعد",emptyBody:"أنشئ طلبًا عندما تحتاج إلى المساعدة. ستبقى المحادثة كاملة هنا.",unavailable:"معلومات الدعم غير متاحة مؤقتًا. طلباتك الحالية محفوظة. يرجى المحاولة قريبًا.",createFailed:"تعذر إنشاء الطلب. سيبقى النص والمرفقات متاحين لإعادة المحاولة.",replyFailed:"لم يتم إرسال ردك. سيبقى هنا لتتمكن من إعادة المحاولة.",reference:"مرجع التذكرة",createdLabel:"تاريخ الإنشاء",updatedLabel:"آخر تحديث",department:"قسم الدعم",priority:"الأولوية",unread:"غير مقروء",latestFromCustomer:"آخر رسالة منك",latestFromSupport:"آخر رسالة من دار طهارة",conversation:"المحادثة",information:"معلومات الطلب",nextAction:"الإجراء التالي المتوقع",resolution:"ملخص الحل",none:"غير متوفر",back:"العودة إلى الدعم",closedExplanation:"هذا الطلب مغلق نهائيًا ولا يمكن إضافة ردود إليه.",createFollowUp:"إنشاء طلب متابعة",customerRole:"أنت",supportRole:"دعم دار طهارة",callRecord:"مكالمة هاتفية",systemEvent:"تحديث النظام",download:"تنزيل",attachmentError:"استخدم حتى 5 ملفات JPG أو PNG أو WebP أو PDF أو نص أو MP4، بحد أقصى 10 ميغابايت لكل ملف.",categoryLabels:categories(["خدمة التنظيف","الاشتراك","موعد أو إعادة جدولة","فاتورة","دفع","إدارة المفاتيح","قفل ذكي","تفاصيل العقار","ملاحظات حول الموظف","ضرر أو غرض مفقود","شكوى","مشكلة تقنية","الوصول إلى الحساب","أخرى"]),statusLabels:statuses(["مفتوح","بانتظار دار طهارة","بانتظار ردك","قيد المعالجة","تم الحل","مغلق"])},
};

Object.assign(supportCopy.nl, { contactMethods:{portal:"Portaal",email:"E-mail",phone:"Telefoon",whatsapp:"WhatsApp"}, priorityLabels:{low:"Laag",normal:"Normaal",high:"Hoog",urgent:"Dringend"} });
Object.assign(supportCopy.fr, { contactMethods:{portal:"Portail",email:"E-mail",phone:"Téléphone",whatsapp:"WhatsApp"}, priorityLabels:{low:"Faible",normal:"Normale",high:"Élevée",urgent:"Urgente"} });
Object.assign(supportCopy.es, { contactMethods:{portal:"Portal",email:"Correo electrónico",phone:"Teléfono",whatsapp:"WhatsApp"}, priorityLabels:{low:"Baja",normal:"Normal",high:"Alta",urgent:"Urgente"} });
Object.assign(supportCopy.de, { contactMethods:{portal:"Portal",email:"E-Mail",phone:"Telefon",whatsapp:"WhatsApp"}, priorityLabels:{low:"Niedrig",normal:"Normal",high:"Hoch",urgent:"Dringend"} });
Object.assign(supportCopy.pt, { contactMethods:{portal:"Portal",email:"E-mail",phone:"Telefone",whatsapp:"WhatsApp"}, priorityLabels:{low:"Baixa",normal:"Normal",high:"Alta",urgent:"Urgente"} });
Object.assign(supportCopy.ar, { contactMethods:{portal:"البوابة",email:"البريد الإلكتروني",phone:"الهاتف",whatsapp:"واتساب"}, priorityLabels:{low:"منخفضة",normal:"عادية",high:"مرتفعة",urgent:"عاجلة"} });
