import { NextRequest, NextResponse } from "next/server";
import { createSubscriptionCheckoutSession } from "@/lib/stripe";
import { serviceInsert, serviceSelect, serviceUpdate, serviceUpsert } from "@/lib/supabase-rpc";

export const runtime="nodejs";
type QuoteRow={id:string;reference:string;status:string;customer_id:string;property_id:string;requested_frequency:string;requested_billing_interval:"monthly"|"annual";revised_monthly_cents:number;revised_annual_cents:number;revised_quote_reason:string|null;revised_quote_status:string;revised_quote_expires_at:string;customers:{full_name:string;preferred_language:"en"|"nl"|"fr"|"ar"|"es"|"de"|"pt";stripe_customer_id:string|null}};
const valid=(token:string)=>/^[0-9a-f-]{36}$/i.test(token);
async function getQuote(token:string){const rows=await serviceSelect<QuoteRow[]>(`home_assessments?revised_quote_token=eq.${token}&select=id,reference,status,customer_id,property_id,requested_frequency,requested_billing_interval,revised_monthly_cents,revised_annual_cents,revised_quote_reason,revised_quote_status,revised_quote_expires_at,customers(full_name,preferred_language,stripe_customer_id)&limit=1`);return rows[0]}

export async function GET(req:NextRequest){const token=req.nextUrl.searchParams.get("token")||"";if(!valid(token))return NextResponse.json({error:"not_found"},{status:404});const row=await getQuote(token);if(!row)return NextResponse.json({error:"not_found"},{status:404});return NextResponse.json({reference:row.reference,status:row.revised_quote_status,monthlyCents:row.revised_monthly_cents,annualCents:row.revised_annual_cents,reason:row.revised_quote_reason,expiresAt:row.revised_quote_expires_at,billingInterval:row.requested_billing_interval,frequency:row.requested_frequency,customerName:row.customers.full_name});}

export async function POST(req:NextRequest){const body=await req.json().catch(()=>({})) as {token?:string;decision?:string};if(!body.token||!valid(body.token)||!["accept","decline"].includes(body.decision||""))return NextResponse.json({error:"invalid_request"},{status:400});const row=await getQuote(body.token);if(!row||row.status!=="needs_revised_quote"||row.revised_quote_status!=="pending"||Date.parse(row.revised_quote_expires_at)<Date.now())return NextResponse.json({error:"quote_unavailable"},{status:409});if(body.decision==="decline"){await serviceUpdate("home_assessments",`id=eq.${row.id}`,{status:"rejected",revised_quote_status:"declined"});await serviceInsert("assessment_events",{assessment_id:row.id,event_type:"revised_quote_declined",from_status:"needs_revised_quote",to_status:"rejected",actor_type:"customer"});return NextResponse.json({ok:true,declined:true});}
  if(!row.customers.stripe_customer_id||!process.env.STRIPE_SECRET_KEY)return NextResponse.json({error:"checkout_not_ready"},{status:503});const monthly=row.revised_monthly_cents;const billed=row.requested_billing_interval==="annual"?row.revised_annual_cents:monthly;const [subscription]=await serviceUpsert<{id:string}[]>("subscriptions",{customer_id:row.customer_id,property_id:row.property_id,assessment_id:row.id,frequency:row.requested_frequency,billing_interval:row.requested_billing_interval,monthly_price_cents:monthly,billed_price_cents:billed,annual_discount_basis_points:row.requested_billing_interval==="annual"?500:0},"assessment_id");const session=await createSubscriptionCheckoutSession({subscriptionId:subscription.id,assessmentId:row.id,customerId:row.customers.stripe_customer_id,locale:row.customers.preferred_language,frequencyLabel:row.requested_frequency,billingInterval:row.requested_billing_interval,amountCents:billed,requestOrigin:req.nextUrl.origin});await serviceUpdate("subscriptions",`id=eq.${subscription.id}`,{stripe_checkout_session_id:session.id});await serviceUpdate("home_assessments",`id=eq.${row.id}`,{status:"approved",revised_quote_status:"accepted"});await serviceInsert("assessment_events",{assessment_id:row.id,event_type:"revised_quote_accepted",from_status:"needs_revised_quote",to_status:"approved",actor_type:"customer"});return NextResponse.json({checkoutUrl:session.url});
}
