"use client";

import * as React from "react";
import { buttonVariants } from "@/components/ui/button";

type Row = { id: string; reference: string; assessment_price_cents: number; payment_status: string; created_at: string; customers: { full_name: string; email: string }; refunds: Array<{ amount_cents: number; status: string }> };

export function ManagerRefunds() {
  const [rows, setRows] = React.useState<Row[]>([]); const [error, setError] = React.useState(""); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/refund", { cache: "no-store" }); const data = await response.json().catch(() => null); setLoading(false); if (!response.ok) setError(data?.error || "Refundable payments could not be loaded."); else setRows(data.assessments); }, []);
  React.useEffect(() => { void load(); }, [load]);
  return <section><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">Payment control</p><h2 className="mt-2 font-serif text-3xl">Refund confirmation</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Every action below creates the Stripe refund immediately and records your manager identity, amount, reason and note in the audit log.</p>{error ? <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p> : null}{loading ? <p className="mt-8 text-sm text-muted-foreground">Loading refundable payments...</p> : null}<div className="mt-6 space-y-4">{rows.map(row => <RefundCard key={row.id} row={row} onDone={load} onError={setError} />)}</div>{!loading && !rows.length ? <div className="mt-8 rounded-2xl border border-border bg-card p-8 text-center text-sm text-muted-foreground">No refundable assessment payments.</div> : null}</section>;
}

function RefundCard({ row, onDone, onError }: { row: Row; onDone: () => Promise<void>; onError: (value: string) => void }) {
  const refunded = (row.refunds || []).filter(item => ["pending", "succeeded"].includes(item.status)).reduce((sum, item) => sum + item.amount_cents, 0); const remaining = Math.max(0, row.assessment_price_cents - refunded);
  const [amount, setAmount] = React.useState(""); const [reason, setReason] = React.useState("requested_by_customer"); const [note, setNote] = React.useState(""); const [confirmed, setConfirmed] = React.useState(false); const [busy, setBusy] = React.useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!confirmed) return; setBusy(true); onError(""); const amountCents = amount ? Math.round(Number(amount) * 100) : undefined; const response = await fetch("/api/admin/refund", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assessmentId: row.id, amountCents, reason, note }) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) { onError(data?.error || "Refund could not be confirmed."); return; } await onDone(); }
  return <form onSubmit={submit} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.2fr_1fr_1fr]"><div><p className="font-semibold">{row.customers.full_name}</p><p className="text-sm text-muted-foreground">{row.customers.email}</p></div><div><p className="text-sm font-medium">{row.reference}</p><p className="text-xs uppercase text-muted-foreground">{row.payment_status.replaceAll("_", " ")}</p></div><div><p className="text-sm font-medium">Remaining {money(remaining)}</p><p className="text-xs text-muted-foreground">Paid {money(row.assessment_price_cents)} · refunded {money(refunded)}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Refund amount in EUR <span className="font-normal text-muted-foreground">(blank = full remainder)</span><input className="input mt-2" type="number" min="0.01" max={(remaining / 100).toFixed(2)} step="0.01" value={amount} onChange={event => setAmount(event.target.value)} /></label><label className="text-sm font-medium">Stripe reason<select className="input mt-2" value={reason} onChange={event => setReason(event.target.value)}><option value="requested_by_customer">Requested by customer</option><option value="duplicate">Duplicate</option><option value="fraudulent">Fraudulent</option></select></label><label className="text-sm font-medium sm:col-span-2">Internal confirmation note <span className="text-accent">*</span><textarea className="input mt-2 min-h-20 resize-y" value={note} onChange={event => setNote(event.target.value)} required /></label></div><label className="mt-4 flex items-start gap-2 text-sm"><input className="mt-1 size-4 accent-primary" type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /><span>I verified the customer, payment and requested amount. I confirm this immediate Stripe refund.</span></label><button disabled={!confirmed || !note.trim() || busy || remaining <= 0} className={`${buttonVariants({ variant: "primary", size: "md" })} mt-4`}>{busy ? "Confirming refund..." : "Confirm refund"}</button></form>;
}
function money(cents: number) { return new Intl.NumberFormat("en", { style: "currency", currency: "EUR" }).format(cents / 100); }
