"use client";
import*as React from"react";import{Search,RefreshCw}from"lucide-react";import{buttonVariants}from"@/components/ui/button";import type{AdminCopy}from"@/i18n/admin-copy";
type SettlementDetails={completedMonths?:number;currentContractMonth?:number;originalTier?:{months?:number};replacementTier?:{months?:number};originalMonthlyCents?:number;replacementMonthlyCents?:number;amountPreviouslyPaidCents?:number;recalculatedConsumedPeriodCents?:number;discountCorrectionCents?:number;remainingMinimumMonths?:number;remainingMinimumTermAmountCents?:number;paymentsAllocatedToRemainingTermCents?:number;includedInvoiceOutstandingCents?:number;includedInvoiceIds?:string[];additionalChargesCents?:number;deepCleanRecoveryCents?:number;creditsCents?:number;settlementPaymentsAlreadyReceivedCents?:number;totalCents?:number};
type SettlementCalculation={original_term_code:string;replacement_term_code:string;completed_months:number;current_contract_month:number;original_monthly_amount_cents:number;replacement_monthly_amount_cents:number;discount_correction_cents:number;remaining_minimum_months:number;remaining_minimum_term_amount_cents:number;included_invoice_ids:string[];credits_cents:number;additional_charges_cents:number;total_cents:number;status:string;confirmed_at:string|null;created_at:string;subscriptions:{billing_interval:"monthly"|"annual";contract_duration_months:number|null}|null};
type AdminCalculation=SettlementCalculation&{id:string;subscription_id:string;customer_id:string;amount_previously_paid_cents:number;recalculated_consumed_amount_cents:number;payments_allocated_to_remaining_term_cents:number;included_invoice_outstanding_cents:number;deep_clean_recovery_cents:number;settlement_payments_received_cents:number;raw_total_cents:number;credit_review_required:boolean;currency:string;expires_at:string;settlement_invoice_id:string|null;customers:{full_name:string;email:string};audit_history:{actor_user_id:string|null;action:string;previous_value:unknown;new_value:unknown;created_at:string}[]};
type InvoiceRow={id:string;invoice_number:string|null;stripe_invoice_id:string|null;status:string;collection_stage:string|null;failed_attempt_count:number;amount_due_cents:number;amount_paid_cents:number;currency:string;created_at:string;invoice_type:"standard"|"early_termination_settlement"|"prepaid_renewal";is_final_settlement:boolean;early_termination_calculation_id:string|null;invoice_details:SettlementDetails|null;early_termination_calculation:SettlementCalculation|null;customers:{full_name:string;email:string}};
function money(cents:number,currency:string):string{return new Intl.NumberFormat("en-IE",{style:"currency",currency:currency.toUpperCase()}).format(cents/100)}
function SettlementBreakdown({row}:{row:InvoiceRow}){const d=row.invoice_details;const calc=row.early_termination_calculation;if(row.invoice_type!=="early_termination_settlement"||!d)return null;const lines:[string,number|undefined][]=[["Original monthly price",d.originalMonthlyCents],["Replacement monthly price",d.replacementMonthlyCents],["Recalculated completed period",d.recalculatedConsumedPeriodCents],["Amount already paid",-Math.abs(d.amountPreviouslyPaidCents||0)],["Discount correction",d.discountCorrectionCents],["Remaining minimum term",d.remainingMinimumTermAmountCents],["Payments allocated to remaining term",-Math.abs(d.paymentsAllocatedToRemainingTermCents||0)],["Outstanding invoices included without re-charging",d.includedInvoiceOutstandingCents],["Additional charges",d.additionalChargesCents],["Deep-clean recovery",d.deepCleanRecoveryCents],["Credits",-Math.abs(d.creditsCents||0)],["Settlement payments received",-Math.abs(d.settlementPaymentsAlreadyReceivedCents||0)],["Final amount",d.totalCents]];return <details className="mt-2 text-xs"><summary className="cursor-pointer font-medium text-primary">View settlement calculation</summary><div className="mt-2 min-w-[320px] rounded-lg border border-border bg-background p-3"><p className="mb-1 text-muted-foreground">Billing method: {calc?.subscriptions?.billing_interval==="annual"?"prepaid":calc?.subscriptions?.billing_interval??"—"}. Calculation status: {calc?.status??"—"}. Confirmed: {calc?.confirmed_at?new Date(calc.confirmed_at).toLocaleString():"—"}.</p><p className="mb-2 text-muted-foreground">Original {d.originalTier?.months??"—"} months → replacement {d.replacementTier?.months??"—"} months; {d.completedMonths??0} completed, current month {d.currentContractMonth??"—"}.</p>{lines.map(([label,value])=><div key={label} className="flex justify-between gap-4 py-0.5"><span>{label}</span><span className="font-medium">{money(value||0,row.currency)}</span></div>)}{d.includedInvoiceIds?.length?<p className="mt-2 text-muted-foreground">Included invoice IDs: {d.includedInvoiceIds.join(", ")}</p>:null}</div></details>}
export function InvoicesAdminClient({copy}:{copy:AdminCopy}){const c=copy.invoicesAdmin;const statusLabels=c.statusLabels;const stageLabels=c.collectionStageLabels;const[rows,setRows]=React.useState<InvoiceRow[]>([]);const[calculations,setCalculations]=React.useState<AdminCalculation[]>([]);const[query,setQuery]=React.useState('');const[filter,setFilter]=React.useState('all');const[busy,setBusy]=React.useState('');const[error,setError]=React.useState('');const load=React.useCallback(async()=>{const[invoicesResponse,calculationsResponse]=await Promise.all([fetch('/api/admin/invoices',{cache:'no-store'}),fetch('/api/admin/early-termination-calculations',{cache:'no-store'})]);if(!invoicesResponse.ok||!calculationsResponse.ok){const status=!invoicesResponse.ok?invoicesResponse.status:calculationsResponse.status;setError(status===401?copy.common.notAuthorized:copy.common.dataUnavailable);return}setRows(await invoicesResponse.json());setCalculations(await calculationsResponse.json());setError('')},[copy.common]);React.useEffect(()=>{load()},[load]);
  async function action(row:InvoiceRow,name:string){
    setBusy(row.id);
    const r=await fetch('/api/admin/invoices/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,action:name})});
    if(!r.ok)setError((await r.json()).error||copy.common.actionFailed);
    await load();setBusy('')
  }
  const visible=rows.filter(r=>(filter==='all'||r.status===filter||r.collection_stage===filter)&&`${r.customers.full_name} ${r.customers.email} ${r.invoice_number||''} ${r.stripe_invoice_id||''}`.toLowerCase().includes(query.toLowerCase()));
  return <div>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-4xl">{c.title}</h1><p className="mt-1 text-sm text-muted-foreground">{rows.length} {c.subtitleSuffix}</p></div><button onClick={load} className={buttonVariants({variant:'outline',size:'md'})}><RefreshCw className="h-4 w-4"/>{copy.common.refresh}</button></header>
    {error?<p className="mt-5 rounded-xl bg-red-500/10 p-3 text-sm text-red-700">{error}</p>:null}
    {calculations.length?<section className="mt-7"><h2 className="font-serif text-2xl">Early-termination calculations</h2><p className="mt-1 text-sm text-muted-foreground">Read-only financial previews and confirmed settlement calculations. Values can only be changed through an audited server workflow.</p><div className="mt-4 overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-secondary/60 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="p-4">Customer</th><th className="p-4">Billing</th><th className="p-4">Term</th><th className="p-4">Periods</th><th className="p-4">Adjustment</th><th className="p-4">Remaining</th><th className="p-4">Credits / charges</th><th className="p-4">Total</th><th className="p-4">Status</th></tr></thead><tbody className="divide-y divide-border">{calculations.map(calc=><tr key={calc.id}><td className="p-4"><p className="font-medium">{calc.customers.full_name}</p><p className="text-xs text-muted-foreground">{calc.customers.email}</p></td><td className="p-4">{calc.subscriptions?.billing_interval==="annual"?"Prepaid":"Monthly paid"}</td><td className="p-4">{calc.original_term_code} → {calc.replacement_term_code}<p className="text-xs text-muted-foreground">{money(calc.original_monthly_amount_cents,calc.currency)} → {money(calc.replacement_monthly_amount_cents,calc.currency)}</p></td><td className="p-4">{calc.completed_months} completed<p className="text-xs text-muted-foreground">current month {calc.current_contract_month}</p></td><td className="p-4">{money(calc.discount_correction_cents,calc.currency)}</td><td className="p-4">{calc.remaining_minimum_months} months<p className="text-xs text-muted-foreground">{money(calc.remaining_minimum_term_amount_cents,calc.currency)}</p></td><td className="p-4">{money(calc.additional_charges_cents,calc.currency)} / {money(calc.credits_cents,calc.currency)}<p className="text-xs text-muted-foreground">{calc.included_invoice_ids.length} included invoice(s)</p></td><td className="p-4 font-semibold">{money(calc.total_cents,calc.currency)}</td><td className="p-4">{calc.status}<p className="text-xs text-muted-foreground">{calc.confirmed_at?`Confirmed ${new Date(calc.confirmed_at).toLocaleString()}`:"Not confirmed"}</p>{calc.audit_history.length?<details className="mt-2 text-xs"><summary className="cursor-pointer text-primary">Audit history ({calc.audit_history.length})</summary><ul className="mt-1 space-y-1">{calc.audit_history.map((entry,index)=><li key={`${entry.created_at}-${index}`}>{new Date(entry.created_at).toLocaleString()} · {entry.action} · {entry.actor_user_id||"system"}</li>)}</ul></details>:null}</td></tr>)}</tbody></table></div></section>:null}
    <div className="mt-7 grid gap-3 sm:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.searchPlaceholder} className="input pl-10"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="input"><option value="all">{copy.common.allStatuses}</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}{Object.entries(stageLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
    <div className="mt-6 overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-secondary/60 text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="p-4">{c.columns.reference}</th><th className="p-4">{c.columns.customer}</th><th className="p-4">{c.columns.total}</th><th className="p-4">{c.columns.outstanding}</th><th className="p-4">{c.columns.status}</th><th className="p-4">{c.columns.collectionStage}</th><th className="p-4">{c.columns.failedAttempts}</th><th className="p-4">{c.columns.nextAction}</th></tr></thead><tbody className="divide-y divide-border">
      {visible.map(row=>{const outstanding=row.amount_due_cents-row.amount_paid_cents;return <tr key={row.id}>
        <td className="p-4 font-medium">{row.invoice_number||row.stripe_invoice_id||row.id.slice(0,8).toUpperCase()}{row.invoice_type==="early_termination_settlement"?<span className="ml-2 rounded-full bg-primary/10 px-2 py-0.5 text-xs font-semibold text-primary align-middle">{c.finalSettlementLabel}</span>:null}<SettlementBreakdown row={row}/></td>
        <td className="p-4"><p className="font-medium">{row.customers.full_name}</p><p className="text-xs text-muted-foreground">{row.customers.email}</p></td>
        <td className="p-4">{money(row.amount_due_cents,row.currency)}</td>
        <td className="p-4">{outstanding>0?money(outstanding,row.currency):'—'}</td>
        <td className="p-4"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{statusLabels[row.status]||row.status}</span></td>
        <td className="p-4">{row.collection_stage?<span className="rounded-full bg-red-500/10 px-2.5 py-1 text-xs font-semibold text-red-700">{stageLabels[row.collection_stage]||row.collection_stage}</span>:<span className="text-xs text-muted-foreground">{c.noStageLabel}</span>}</td>
        <td className="p-4">{row.failed_attempt_count}</td>
        <td className="p-4"><div className="flex flex-wrap gap-2">
          {row.collection_stage?<><button disabled={busy===row.id} onClick={()=>action(row,'resend_notice')} className={buttonVariants({variant:'outline',size:'sm'})}>{c.actions.resendNotice}</button><button disabled={busy===row.id} onClick={()=>action(row,'generate_replacement_link')} className={buttonVariants({variant:'outline',size:'sm'})}>{c.actions.generateReplacementLink}</button></>:null}
        </div></td>
      </tr>})}
      {!visible.length?<tr><td colSpan={8} className="p-10 text-center text-muted-foreground">{c.noMatch}</td></tr>:null}
    </tbody></table></div>
  </div>
}
