"use client";
import * as React from "react";
import { CalendarDays, CheckCircle2, ExternalLink, LogOut, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

type Assessment={id:string;reference:string;status:string;payment_status:string;preferred_date:string;preferred_time_slot:string;requested_frequency:string;requested_billing_interval:string;estimated_monthly_cents:number|null;revised_monthly_cents:number|null;assessment_price_cents:number;assessment_notes:string|null;stripe_checkout_session_id:string|null;assigned_cleaner_id:string|null;assigned_inspector_id:string|null;customers:{full_name:string;email:string;phone:string;preferred_language:string};properties:{address_line1:string;city:string;declared_size_m2:number;declared_bedrooms:number;declared_bathrooms:number;pets:boolean;smoking:boolean;declared_condition:string};subscriptions:Array<{id:string;status:string;stripe_subscription_id:string|null}>|null};
const labels:Record<string,string>={awaiting_payment:"Awaiting payment",assessment:"Assessment scheduled",pending_review:"Pending review",approved:"Approved",needs_revised_quote:"Revised quote",rejected:"Rejected",subscription_active:"Subscription active",paused:"Paused",cancelled:"Cancelled"};

export function AdminClient(){
 const [token,setToken]=React.useState("");const [ready,setReady]=React.useState(false);const [rows,setRows]=React.useState<Assessment[]>([]);const [filter,setFilter]=React.useState("all");const [query,setQuery]=React.useState("");const [busy,setBusy]=React.useState("");const [error,setError]=React.useState("");
 const load=React.useCallback(async()=>{const r=await fetch("/api/admin/assessments",{cache:"no-store"});if(r.status===401){setReady(false);return}if(!r.ok){setError("Admin data is not configured yet.");return}setRows(await r.json());setReady(true)},[]);
 React.useEffect(()=>{load()},[load]);
 async function login(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/auth",{method:"POST",headers:{Authorization:`Bearer ${token}`}});if(!r.ok){setError(r.status===503?"Admin credentials are not configured.":"Invalid access token.");return}setToken("");setReady(true);load()}
 async function action(row:Assessment,name:string){let notes="";let revisedMonthlyCents:number|undefined;if(["complete","revise","reject","cancel"].includes(name))notes=window.prompt("Internal notes / customer-facing reason")||"";if(name==="revise"){const euros=Number(window.prompt("Revised monthly price in EUR"));if(!Number.isFinite(euros)||euros<0)return;revisedMonthlyCents=Math.round(euros*100)}setBusy(row.id);setError("");const r=await fetch("/api/admin/assessments/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,action:name,notes,revisedMonthlyCents})});if(!r.ok)setError((await r.json()).error||"Action failed");await load();setBusy("")}
 async function assign(row:Assessment){const cleanerId=window.prompt("Cleaner staff UUID (blank to unassign)",row.assigned_cleaner_id||"");if(cleanerId===null)return;const inspectorId=window.prompt("Inspector staff UUID (blank to unassign)",row.assigned_inspector_id||"");if(inspectorId===null)return;setBusy(row.id);const r=await fetch("/api/admin/assessments/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,action:"assign",cleanerId,inspectorId})});if(!r.ok)setError((await r.json()).error||"Assignment failed");await load();setBusy("")}
 async function message(row:Assessment){const message=window.prompt(`WhatsApp message to ${row.customers.full_name}`);if(!message)return;setBusy(row.id);const r=await fetch("/api/admin/assessments/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,action:"message",message})});if(!r.ok)setError((await r.json()).error||"Message failed");setBusy("")}
 async function subscriptionCheckout(row:Assessment){const subscription=row.subscriptions?.[0];if(!subscription)return;setBusy(row.id);const r=await fetch("/api/admin/subscription-checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscriptionId:subscription.id})});const data=await r.json();if(data.checkoutUrl)await navigator.clipboard.writeText(data.checkoutUrl);else setError(data.error||"Could not create link");setBusy("");if(data.checkoutUrl)window.alert("Secure subscription checkout link copied to the clipboard.")}
 const visible=rows.filter(r=>(filter==="all"||r.status===filter)&&`${r.reference} ${r.customers.full_name} ${r.customers.email} ${r.properties.city}`.toLowerCase().includes(query.toLowerCase()));
 if(!ready)return <main className="flex min-h-screen items-center justify-center bg-secondary/30 p-6"><form onSubmit={login} className="w-full max-w-md rounded-[2rem] border border-border bg-card p-8 shadow-lift"><ShieldCheck className="h-10 w-10 text-primary"/><h1 className="mt-5 font-serif text-3xl">Dar Tahara Operations</h1><p className="mt-2 text-sm text-muted-foreground">Enter the private admin API token. Access expires after eight hours.</p><label className="mt-6 block text-sm font-medium">Access token<input type="password" autoFocus value={token} onChange={e=>setToken(e.target.value)} className="input mt-2"/></label>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<button className={cn(buttonVariants({variant:"primary",size:"lg"}),"mt-6 w-full")}>Open operations</button></form></main>;
 return <main className="min-h-screen bg-secondary/30 p-4 sm:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-accent">Private operations</p><h1 className="mt-2 font-serif text-4xl">Home Assessments</h1><p className="mt-1 text-sm text-muted-foreground">{rows.length} bookings · payment-gated workflow</p></div><div className="flex gap-2"><button onClick={load} className={buttonVariants({variant:"outline",size:"md"})}><RefreshCw className="h-4 w-4"/>Refresh</button><button onClick={async()=>{await fetch("/api/admin/auth",{method:"DELETE"});setReady(false)}} className={buttonVariants({variant:"ghost",size:"md"})}><LogOut className="h-4 w-4"/>Sign out</button></div></header>
 {error&&<p className="mt-5 rounded-xl bg-red-500/10 p-3 text-sm text-red-700">{error}</p>}<div className="mt-7 grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, customer or city" className="input pl-10"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className="input"><option value="all">All statuses</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
 <div className="mt-6 space-y-4">{visible.map(row=><article key={row.id} className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-muted-foreground">{row.reference}</span><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{labels[row.status]||row.status}</span><span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold",row.payment_status==="paid"?"bg-emerald-500/10 text-emerald-700":"bg-amber-500/10 text-amber-700")}>{row.payment_status}</span></div><h2 className="mt-2 font-serif text-2xl">{row.customers.full_name}</h2><p className="text-sm text-muted-foreground">{row.customers.email} · {row.customers.phone}</p></div><div className="text-end"><p className="flex items-center gap-2 font-medium"><CalendarDays className="h-4 w-4 text-accent"/>{row.preferred_date} · {row.preferred_time_slot}</p><p className="mt-1 text-sm text-muted-foreground">{row.properties.address_line1}, {row.properties.city}</p></div></div>
 <dl className="mt-5 grid gap-3 rounded-xl bg-secondary/50 p-4 text-sm sm:grid-cols-4"><div><dt className="text-muted-foreground">Property</dt><dd>{row.properties.declared_size_m2} m² · {row.properties.declared_bedrooms} bed · {row.properties.declared_bathrooms} bath</dd></div><div><dt className="text-muted-foreground">Condition</dt><dd>{row.properties.declared_condition}{row.properties.pets?" · pets":""}{row.properties.smoking?" · smoking":""}</dd></div><div><dt className="text-muted-foreground">Requested plan</dt><dd>{row.requested_frequency} · {row.requested_billing_interval}</dd></div><div><dt className="text-muted-foreground">Estimate</dt><dd>{row.estimated_monthly_cents===null?"Quote required":`${(row.estimated_monthly_cents/100).toFixed(0)} EUR/month`}</dd></div></dl>
 <div className="mt-4 flex flex-wrap gap-2">{row.status==="assessment"&&<button disabled={busy===row.id} onClick={()=>action(row,"complete")} className={buttonVariants({variant:"primary",size:"sm"})}><CheckCircle2 className="h-4 w-4"/>Complete assessment</button>}{row.status==="pending_review"&&<><button disabled={busy===row.id} onClick={()=>action(row,"approve")} className={buttonVariants({variant:"primary",size:"sm"})}>Approve plan</button><button disabled={busy===row.id} onClick={()=>action(row,"revise")} className={buttonVariants({variant:"outline",size:"sm"})}>Revised quote</button><button disabled={busy===row.id} onClick={()=>action(row,"reject")} className={buttonVariants({variant:"ghost",size:"sm"})}>Reject</button></>}{row.status==="approved"&&row.subscriptions?.[0]&&<button disabled={busy===row.id} onClick={()=>subscriptionCheckout(row)} className={buttonVariants({variant:"gold",size:"sm"})}><ExternalLink className="h-4 w-4"/>Copy subscription payment link</button>}<button disabled={busy===row.id} onClick={()=>assign(row)} className={buttonVariants({variant:"outline",size:"sm"})}>Assign team</button><button disabled={busy===row.id} onClick={()=>message(row)} className={buttonVariants({variant:"outline",size:"sm"})}>Message customer</button>{row.stripe_checkout_session_id&&<button onClick={()=>navigator.clipboard.writeText(row.stripe_checkout_session_id||"")} className={buttonVariants({variant:"ghost",size:"sm"})}>Copy Stripe payment ID</button>}{!["cancelled","rejected","subscription_active"].includes(row.status)&&<button disabled={busy===row.id} onClick={()=>action(row,"cancel")} className={buttonVariants({variant:"ghost",size:"sm"})}>Cancel</button>}</div></article>)}{visible.length===0&&<div className="rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground">No assessments match this view.</div>}</div></div></main>
}
