"use client";
import * as React from "react";
import type {Locale} from "@/i18n/config";
import {buttonVariants} from "@/components/ui/button";
import {formatMoneyFromCents} from "@/lib/assessment";
import {CheckCircle2} from "lucide-react";

const copy:Record<Locale,{title:string;intro:string;monthly:string;annual:string;reason:string;accept:string;decline:string;loading:string;declined:string;unavailable:string}>={
en:{title:"Your revised home-care plan",intro:"Your Home Assessment identified a material difference from the original booking. Review the personalised plan below.",monthly:"Revised monthly price",annual:"Revised annual price",reason:"Assessment note",accept:"Accept and continue to payment",decline:"Decline subscription",loading:"Loading your secure quote…",declined:"The subscription offer has been declined.",unavailable:"This quote is no longer available."},
nl:{title:"Uw aangepaste woningzorgplan",intro:"De woningbeoordeling liet een belangrijk verschil met de oorspronkelijke boeking zien. Bekijk uw plan hieronder.",monthly:"Aangepaste maandprijs",annual:"Aangepaste jaarprijs",reason:"Beoordelingsnotitie",accept:"Accepteren en veilig betalen",decline:"Abonnement weigeren",loading:"Uw beveiligde aanbod laden…",declined:"Het abonnementsaanbod is geweigerd.",unavailable:"Dit aanbod is niet meer beschikbaar."},
fr:{title:"Votre plan d’entretien révisé",intro:"L’Évaluation du Domicile a relevé une différence importante. Vérifiez votre plan personnalisé ci-dessous.",monthly:"Prix mensuel révisé",annual:"Prix annuel révisé",reason:"Note d’évaluation",accept:"Accepter et passer au paiement",decline:"Refuser l’abonnement",loading:"Chargement de votre offre sécurisée…",declined:"L’offre d’abonnement a été refusée.",unavailable:"Cette offre n’est plus disponible."},
ar:{title:"خطة العناية المعدلة لمنزلك",intro:"أظهر تقييم المنزل فرقاً جوهرياً عن الحجز الأصلي. راجع خطتك المخصصة أدناه.",monthly:"السعر الشهري المعدل",annual:"السعر السنوي المعدل",reason:"ملاحظة التقييم",accept:"الموافقة والمتابعة إلى الدفع",decline:"رفض الاشتراك",loading:"جارٍ تحميل العرض الآمن…",declined:"تم رفض عرض الاشتراك.",unavailable:"لم يعد هذا العرض متاحاً."},
es:{title:"Su plan de cuidado revisado",intro:"La Evaluación del Hogar detectó una diferencia importante. Revise su plan personalizado.",monthly:"Precio mensual revisado",annual:"Precio anual revisado",reason:"Nota de evaluación",accept:"Aceptar y continuar al pago",decline:"Rechazar suscripción",loading:"Cargando su oferta segura…",declined:"La oferta de suscripción ha sido rechazada.",unavailable:"Esta oferta ya no está disponible."},
de:{title:"Ihr angepasster Pflegeplan",intro:"Die Hauseinschätzung ergab eine wesentliche Abweichung. Prüfen Sie Ihren persönlichen Plan.",monthly:"Angepasster Monatspreis",annual:"Angepasster Jahrespreis",reason:"Einschätzungsnotiz",accept:"Annehmen und sicher bezahlen",decline:"Abonnement ablehnen",loading:"Sicheres Angebot wird geladen…",declined:"Das Abonnementangebot wurde abgelehnt.",unavailable:"Dieses Angebot ist nicht mehr verfügbar."},
pt:{title:"O seu plano de cuidado revisto",intro:"A Avaliação da Casa identificou uma diferença importante. Reveja o plano personalizado.",monthly:"Preço mensal revisto",annual:"Preço anual revisto",reason:"Nota da avaliação",accept:"Aceitar e continuar para pagamento",decline:"Recusar subscrição",loading:"A carregar a proposta segura…",declined:"A proposta de subscrição foi recusada.",unavailable:"Esta proposta já não está disponível."}};
type Quote={reference:string;status:string;monthlyCents:number;annualCents:number;reason:string|null;billingInterval:"monthly"|"annual"};
export function RevisedQuoteClient({locale,token}:{locale:Locale;token:string}){const c=copy[locale];const[data,setData]=React.useState<Quote|null>(null);const[state,setState]=React.useState<"loading"|"ready"|"busy"|"declined"|"error">("loading");React.useEffect(()=>{fetch(`/api/assessment/revised-quote?token=${encodeURIComponent(token)}`).then(async r=>{if(!r.ok)throw 0;setData(await r.json());setState("ready")}).catch(()=>setState("error"))},[token]);async function decide(decision:"accept"|"decline"){setState("busy");const r=await fetch("/api/assessment/revised-quote",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,decision})});const value=await r.json();if(value.checkoutUrl)location.assign(value.checkoutUrl);else if(value.declined)setState("declined");else setState("error")}
return <main className="flex min-h-[70vh] items-center justify-center px-6 py-20"><div className="w-full max-w-2xl rounded-[2rem] border border-border bg-card p-8 shadow-lift sm:p-12"><p className="text-xs font-semibold uppercase tracking-[.24em] text-accent">Dar Tahara</p><h1 className="mt-3 font-serif text-4xl">{c.title}</h1>{state==="loading"&&<p className="mt-5 text-muted-foreground">{c.loading}</p>}{state==="error"&&<p className="mt-5 text-red-700">{c.unavailable}</p>}{state==="declined"&&<p className="mt-7 flex gap-3 text-foreground"><CheckCircle2 className="text-primary"/>{c.declined}</p>}{data&&["ready","busy"].includes(state)&&<><p className="mt-4 leading-relaxed text-muted-foreground">{c.intro}</p><div className="mt-7 rounded-2xl bg-secondary/50 p-5"><p className="font-mono text-xs text-muted-foreground">{data.reference}</p><div className="mt-3 flex justify-between"><span>{c.monthly}</span><strong>{formatMoneyFromCents(data.monthlyCents,locale)}</strong></div>{data.billingInterval==="annual"&&<div className="mt-2 flex justify-between"><span>{c.annual}</span><strong>{formatMoneyFromCents(data.annualCents,locale)}</strong></div>}{data.reason&&<div className="mt-4 border-t border-border pt-4"><span className="text-sm text-muted-foreground">{c.reason}</span><p className="mt-1">{data.reason}</p></div>}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button disabled={state==="busy"} onClick={()=>decide("accept")} className={buttonVariants({variant:"gold",size:"lg"})}>{c.accept}</button><button disabled={state==="busy"} onClick={()=>decide("decline")} className={buttonVariants({variant:"outline",size:"lg"})}>{c.decline}</button></div></>}</div></main>}
